service: page-to-pdf
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.9
  region: sa-east-1
  stage: production
  apiGateway:
    binaryMediaTypes:
      - "application/pdf"
plugins:
  - serverless-domain-manager
  - serverless-python-requirements
  - serverless-offline
custom:
  pythonRequirements:
     dockerizePip: non-linux
  customDomain:
    rest:
      domainName: {your_domain}
      certificateName: {your_certificate}
      hostZoneId: {your_zone_id}
      endpointType: regional
      securityPolicy: tls_1_2
      basePath: ''
      apiType: rest
      createRoute53Record: true
package:
  exclude:
    - node_modules/**
  excludeDevDependencies: true
functions:
  get:
    handler: handler.get
    events:
      - http:
          path: pdf
          method: get
          cors: true

